### ISSUE TITLE
Get PDF URL from PubMed?

### ISSUE THREAD

**Issue by dbolser** [zotero/translation-server#112] opened 2020-03-11 17:02 UTC
I'm sure I'm being dumb, but none of my /web /search or /export API calls return the URL of the PDF.

What am I doing wrong?

Many thanks,
Dan

**Comment by dstillman** [comment] 2020-03-11 17:04
Duplicate of https://github.com/zotero/translation-server/issues/97

**Closed as completed by dstillman** 2020-03-11 17:04 UTC

**Comment by dbolser** [comment] 2020-03-11 17:34
Thanks.
